# permissions for end users to view octopingers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octopinger-viewer-role
rules:
- apiGroups:
  - octopinger.io
  resources:
  - octopingers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octopinger.io
  resources:
  - octopingers/status
  verbs:
  - get
