apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  octopinger-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octopinger-controller
subjects:
- kind: ServiceAccount
  name: octopinger-controller
  namespace: octopinger
