## Octopinger configuration
## Ref: https://github.com/ionos-cloud/octopinger
##

# -- Provide a name in place of `octopinger`
nameOverride: octopinger
# -- String to fully override `"octopinger.fullname"`
fullnameOverride: ""
# -- Override the Kubernetes version, which is used to evaluate certain manifests
kubeVersionOverride: ""

## Custom resource configuration
crds:
  # -- Install and upgrade CRDs
  install: true
  # -- Keep CRDs on chart uninstall
  keep: true
  # -- Annotations to be added to all CRDs
  annotations: {}

## Globally shared configuration
global:
  # -- Common labels for the all resources
  additionalLabels: {}
    # app: octopinger

  # Default image used by all components
  image:
    # -- If defined, a repository applied to all Octopinger deployments
    repository: ghcr.io/ionos-cloud/octopinger/octopinger
    # -- Overrides the global Octopinger image tag whose default is the chart appVersion
    tag: ""
    # -- If defined, a imagePullPolicy applied to all Octopinger deployments
    imagePullPolicy: IfNotPresent

  # -- Secrets with credentials to pull images from a private registry
  imagePullSecrets: []

## Octopinger Configs
configs: