apiVersion: octopinger.io/v1alpha1
kind: Octopinger
metadata:
  name: demo
spec:
  image: ghcr.io/ionos-cloud/octopinger/octopinger:v0.0.33
  label: octopinger
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
  probes:
    - type: icmp
      enabled: true
      properties:
        timeout: 1m
        interval: 1m
        external: |
          1.1.1.1