apiVersion: octopinger.io/v1alpha1
kind: Octopinger
metadata:
  name: demo
spec:
  label: octopinger
  config:
    icmp:
      enable: true
    dns:
      enable: false
  template:
    image: ghcr.io/ionos-cloud/octopinger/octopinger:v0.1.0