apiVersion: octopinger.io/v1alpha1
kind: Octopinger
metadata:
  name: demo
spec:
  label: octopinger
  config:
    icmp:
      enable: true
    dns:
      enable: true
      servers: 8.8.8.8
      names:
       - www.google.com
       - www.ionos.com
  template:
    image: ghcr.io/ionos-cloud/octopinger/octopinger:v0.1.6-alpha.2