apiVersion: octopinger.io/v1alpha1
kind: Octopinger
metadata:
  name: demo
spec:
  image: ghcr.io/ionos-cloud/octopinger/octopinger:0.0.29
  label: octopinger
  probes:
    - type: icmp
      enabled: true
      properties:
        timeout: 1m
        interval: 1m
        external: |
          1.1.1.1