apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "octopinger.controller.fullname" . }}
  labels:
    {{- include "octopinger.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "octopinger.controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "octopinger.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
